package shared

// WorkerRegisterRequest is sent by a worker to the master on startup.
type WorkerRegisterRequest struct {
	ID      string `json:"id"`      // UUID generated by the worker
	Name    string `json:"name"`    // human‑readable, e.g. "worker-go"
	Address string `json:"address"` // full URL like "http://192.168.1.101:8081"
}

// WorkerRegisterResponse is the master's reply.
type WorkerRegisterResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}